name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    name: Lint
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup JFrog
        uses: ./.github/actions/setup-jfrog

      - name: Set up Go Toolchain
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.20.x'
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4
        with:
          version: 'v1.51'
  build-and-test:
    name: Test and Build
    strategy:
      matrix:
        go-version: [1.20.x]
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup JFrog
        uses: ./.github/actions/setup-jfrog

      - name: Set up Go Toolchain
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Cache Go artifacts
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Get dependencies
        run: |
          if ! command -v make &> /dev/null ; then
            echo "Installing make"
            apt-get update
            apt-get install -y make
          fi
          if ! command -v git &> /dev/null ; then
            echo "Installing git"
            apt-get update
            apt-get install -y git
          fi
          go get -v -t -d ./...

      - name: Test
        run: make test
        env:
          CGO_ENABLED: 0

      - name: Test-Race
        run: make test-race

      - name: Build
        run: make linux
